export const REQUEST_TIMELINE = 'REQUEST_TIMELINE';
export const RESOLVE_TIMELINE = 'RESOLVE_TIMELINE';
export const REJECT_TIMELINE = 'REJECT_TIMELINE';

export const REQUEST_FEED = 'REQUEST_FEED';
export const RESOLVE_FEED = 'RESOLVE_FEED';
export const REJECT_FEED = 'REJECT_FEED';
