export const REQUEST_TIMELINE = 'REQUEST_TIMELINE';
export const RESOLVE_TIMELINE = 'RESOLVE_TIMELINE';
export const REJECT_TIMELINE = 'REJECT_TIMELINE';
export const REQUEST_FEED = 'REQUEST_FEED';
export const RESOLVE_FEED = 'RESOLVE_FEED';
export const REJECT_FEED = 'REJECT_FEED';
export const FEED_NEXT_PAGE = 'FEED_NEXT_PAGE';
export const FEED_NEXT_PAGE_SAGA = 'FEED_NEXT_PAGE_SAGA';
export const SWITCH_IMAGE_STATUS = 'SWITCH_IMAGE_STATUS';
export const NAV_OPEN_FEED = 'NAV_OPEN_FEED';
export const NAV_BACK = 'NAV_BACK';
//# sourceMappingURL=actionType.js.map